"""add job appln

Revision ID: 14860e3b0d8c
Revises: a3525749865c
Create Date: 2025-11-25 15:53:51.074667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14860e3b0d8c'
down_revision: Union[str, Sequence[str], None] = 'a3525749865c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('appication_id', sa.Integer(), nullable=False))
    op.add_column('job_applications', sa.Column('resume_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'job_applications', 'job_posts', ['job_post_id'], ['id'])
    op.add_column('job_posts', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'status')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_column('job_applications', 'resume_url')
    op.drop_column('job_applications', 'appication_id')
    # ### end Alembic commands ###
