"""add status

Revision ID: 899001ef544b
Revises: 14860e3b0d8c
Create Date: 2025-11-25 16:08:14.764753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899001ef544b'
down_revision: Union[str, Sequence[str], None] = '14860e3b0d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.drop_constraint(op.f('job_boards_logo_url_key'), 'job_boards', type_='unique')
    op.alter_column('job_posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_unique_constraint(op.f('job_boards_logo_url_key'), 'job_boards', ['logo_url'], postgresql_nulls_not_distinct=False)
    op.drop_table('job_applications')
    # ### end Alembic commands ###
