"""add logo url

Revision ID: 9085a66e7e5f
Revises: 1fa5d65ef3c4
Create Date: 2025-11-24 16:08:28.720405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9085a66e7e5f'
down_revision: Union[str, Sequence[str], None] = '1fa5d65ef3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_boards', sa.Column('logo_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'job_boards', ['logo_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_boards', type_='unique')
    op.drop_column('job_boards', 'logo_url')
    # ### end Alembic commands ###
