"""add job appln

Revision ID: a3525749865c
Revises: 9085a66e7e5f
Create Date: 2025-11-25 15:24:16.053383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3525749865c'
down_revision: Union[str, Sequence[str], None] = '9085a66e7e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('job_post_id')
    )
    op.drop_constraint(op.f('job_boards_logo_url_key'), 'job_boards', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('job_boards_logo_url_key'), 'job_boards', ['logo_url'], postgresql_nulls_not_distinct=False)
    op.drop_table('job_applications')
    # ### end Alembic commands ###
